[package]
name = "switchit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "switchit"

[dependencies]
eframe = "0.18.0"
image = "0.24.2"